const STATS = 'quiz/STATS'

export const FETCH_STUDENT_STATS = `${STATS}/FETCH_STUDENT_STATS`
export const FETCH_STUDENT_STATS_SUCCESS = `${STATS}/FETCH_STUDENT_STATS_SUCCESS`
export const FETCH_STUDENT_STATS_FAILURE = `${STATS}/FETCH_STUDENT_STATS_FAILURE`

export const FETCH_ALL_EXAM_STATS = `${STATS}/FETCH_ALL_EXAM_STATS`
export const FETCH_ALL_EXAM_STATS_SUCCESS = `${STATS}/FETCH_ALL_EXAM_STATS_SUCCESS`
export const FETCH_ALL_EXAM_STATS_FAILURE = `${STATS}/FETCH_ALL_EXAM_STATS_FAILURE`

export const FETCH_SCHOOL_STATS = `${STATS}/FETCH_SCHOOL_STATS`
export const FETCH_SCHOOL_STATS_SUCCESS = `${STATS}/FETCH_SCHOOL_STATS_SUCCESS`
export const FETCH_SCHOOL_STATS_FAILURE = `${STATS}/FETCH_SCHOOL_STATS_FAILURE`

export const PERIOD_ALL = 'all'
export const PERIOD_CURRENT = 'current'
export const PERIOD_WEEK = 'week'
export const PERIOD_WEEK3 = 'week3'

export const SET_PERIOD = `${STATS}/SET_PERIOD`
