const STUDENT = 'quiz/STUDENT'

export const FETCH_LIST = `${STUDENT}/FETCH_LIST`
export const FETCH_LIST_SUCCESS = `${STUDENT}/FETCH_LIST_SUCCESS`
export const FETCH_LIST_FAILURE = `${STUDENT}/FETCH_LIST_FAILURE`

export const CREATE = `${STUDENT}/CREATE`
export const CREATE_SUCCESS = `${STUDENT}/CREATE_SUCCESS`
export const CREATE_FAILURE = `${STUDENT}/CREATE_FAILURE`

export const DESTROY = `${STUDENT}/DESTROY`
export const DESTROY_SUCCESS = `${STUDENT}/DESTROY_SUCCESS`
export const DESTROY_FAILURE = `${STUDENT}/DESTROY_FAILURE`

export const EDITOR_CREATE = `${STUDENT}/EDITOR_CREATE`
export const EDITOR_UPDATE = `${STUDENT}/EDITOR_UPDATE`
export const EDITOR_CLOSE = `${STUDENT}/EDITOR_CLOSE`
