const TOPIC = 'quiz/TOPIC'

export const SELECT_TOPIC = `${TOPIC}/SELECT`

export const FETCH_TOPIC_ERRORS = `${TOPIC}/FETCH_TOPIC_ERRORS`
export const FETCH_TOPIC_ERRORS_SUCCESS = `${TOPIC}/FETCH_TOPIC_ERRORS_SUCCESS`
export const FETCH_TOPIC_ERRORS_FAILURE = `${TOPIC}/FETCH_TOPIC_ERRORS_FAILURE`

export const FETCH_TOPIC_LIST = `${TOPIC}/FETCH_TOPIC_LIST`
export const FETCH_TOPIC_LIST_SUCCESS = `${TOPIC}/FETCH_TOPIC_LIST_SUCCESS`
export const FETCH_TOPIC_LIST_FAILURE = `${TOPIC}/FETCH_TOPIC_LIST_FAILURE`

export const FETCH_TOPIC_SINGLE_BY_ID = `${TOPIC}/FETCH_SINGLE_BY_ID`
export const FETCH_TOPIC_SINGLE_BY_ID_SUCCESS = `${TOPIC}/FETCH_SINGLE_BY_ID_SUCCESS`
export const FETCH_TOPIC_SINGLE_BY_ID_FAILURE = `${TOPIC}/FETCH_SINGLE_BY_ID_FAILURE`
